### PR TITLE
fix: remove EXERTNALLY-MANAGED on Debian12

### PR DESCRIPTION
**Pull request by barnabasbusa**
Resolves: https://github.com/geerlingguy/ansible-role-pip/issues/57

### CODE REVIEW

**Review by geerlingguy — CHANGES_REQUESTED** [review]
The way these tasks are laid out won't work on Ubuntu or other non-Debian distros, as the py3ver variable isn't defined.

It might be better to just add that 2nd task alone, with the when clause from the top task merged in.

**Comment by barnabasbusa** [comment]
Changes made according to your feedback. Also bumped the CI versions, as I saw some deprecation notices with the earlier versions. And bumped the images on which molecule runs on.

**Comment by fbermel** [comment]
Hi,

I'm facing a similar issue. What about just doing this to remove the `EXTERNALLY-MANAGED` file?

```
- name: Remove EXTERNALLY-MANAGED file
  ansible.builtin.file:
    path: /usr/lib/python3.{{ ansible_python.version.minor }}/EXTERNALLY-MANAGED
    state: absent
````

This will keep working even if the system python changes.

**Comment by crazychatting** [comment]
Hi,
what is needed to get this merged? I´m also facing this issue and saw this PR from months ago...

**Comment by julianborghuis** [comment]
sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED

Then it works ;)

**Pull request merged**
