### PR TITLE
remove trailing whitespace

### PR DESCRIPTION
**Pull request by jcgruenhage**
This is probably a bit opinionated, but removing trailing whitespace sounds like
a good idea to me.

### CODE REVIEW

**Comment by jcgruenhage** [comment]
not stale, still current.

**Comment by geerlingguy** [comment]
Typically I leave the indents inline in a large block of examples, to show it's one continuous example...

However I've started moving towards using backticks (`\`\`\``) to separate code blocks because I can add `\`\`\`yaml` and have syntax highlighting even!

**Comment by jcgruenhage** [comment]
Do you want me to update this PR with code blocks instead? Would be a good solution to this too :)

**Comment by geerlingguy** [comment]
@jcgruenhage - Yeah, if you rebase and use code blocks, happy to merge it!

**Pull request closed without merging**
